# this file is basically just copied from hashicorp's thing, with various auto-tags removed

name: Upgrade Dependencies

on:
  workflow_dispatch:
    secrets:
      CLASSIC_TOKEN:
        required: true
        description: 'Classic token'

jobs:
  upgrade:
    name: upgrade deps
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: auto-dependency-upgrades
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # checkout
      - uses: actions/checkout@v3 # should be a sha, but eh
      # activate go
      - uses: actions/setup-go@v4
      - name: update deps
        run: |
          go list -u -m -json all | jq -r 'select(.Indirect != true and .Update != null) | .Path+"@"+.Update.Version' | xargs -L1 go get
          go mod tidy
      - name: detect changes
        id: changes
        run : |
          echo "count=$(git status --porcelain=v1 2>/dev/null | wc -l)" >> "$GITHUB_OUTPUT"
      - name: commit/push
        if: steps.changes.outputs.count > 0
        id: git
        run: |
          git config user.name kpc-bot
          git config user.email kpc-bot@users.noreply.github.com
          git add .
          git commit -m "Automated dependency upgrades"
          echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          git push -f origin ${{ github.ref_name }}:"$BRANCH_NAME"
      # this is the new step
      - name: run target checks
        id: dispatch
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.CLASSIC_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/kpcraig/gha-target/dispatches \
          -d '{"event_type":"dispatch_test","client_payload":{"sha":"${{steps.git.outputs.sha}}","repo":"gha-target"}}'